### ISSUE TITLE
USER STORY: Initial Project Planning

### ISSUE THREAD

**Issue by Aylamccarthy** [Aylamccarthy/madisons-patisserie#1]
## Description: 
As **the developer**, I can **plan my project building process with the help of visual tools such as flowchart and wireframes** so that **I can visually map out the apps system logic**

## Acceptance criteria:
- [x] Create clear and concise flowchart using LucidChart.
- [x] Create a simple but effective wireframes.
- [x] Provide a clear business model
- [x] Use Agile methodology for the entire building process

## Tasks
- [x] Create the app's flowchart
- [x] Create wireframes
- [x]  Create project on github, create user stories and  use the kanban board to facilitate the building process
