### ISSUE TITLE
USER STORY: PRODUCTS PAGE

### ISSUE THREAD

**Issue by Aylamccarthy** [Aylamccarthy/madisons-patisserie#10]
## Description: 
As **a user**, I can **see a catalogue of all the products, grouped by categories** so that **I can decide which product to purchase**

## Acceptance criteria:
- [x] The website has a 'Products' page
- [x] The products are grouped by categories

## Tasks
- [x] Create a 'Products' page
- [x] Create a list of products with price and short description
