### ISSUE TITLE
USER STORY: PRODUCT DETAILS page

### ISSUE THREAD

**Issue by Aylamccarthy** [Aylamccarthy/madisons-patisserie#11]
## Description: 
As **a user**, I can **see a product's full description** so that **I can easily decide which one to buy**

## Acceptance criteria:
- [x] The website has a product details page
- [x] The user can see each products specifications such as short description and price

## Tasks
- [x] Create a product details page
- [x] Add a feature for adding products to the shopping bag from the 'Details' page
