### ISSUE TITLE
USER STORY: PRODUCT MANAGEMENT

### ISSUE THREAD

**Issue by Aylamccarthy** [Aylamccarthy/madisons-patisserie#12]
## Description: 
As **an admin**, I can **add new products to the catalogue and edit product details** so that **it reflects the existing inventory and the website is always up to date with the current stock**

## Acceptance criteria:
- [x] Admin can add products
- [x] Admin can edit products to keep in line with the existing inventory

## Tasks
- [x] Implement features for admin to add and edit products
- [x] Implement features for admin to delete products
