### ISSUE TITLE
USER STORY: WISHLIST

### ISSUE THREAD

**Issue by Aylamccarthy** [Aylamccarthy/madisons-patisserie#14]
## Description: 
As **a logged in user**, I can **add/remove products from my Wishlist** so that **I can easily find them again should I change my mind and want to purchase**

## Acceptance criteria:
- [x] Logged in users can add/remove products from their Wishlist
- [x] Logged in users can add products  to their shopping bag from their Wishlist

## Tasks
- [x] Create a page to display all products added to the Wishlist
- [x] Add a feature to be able to add products from the wishlist to the shopping bag
