### ISSUE TITLE
USER STORY: SHOPPING BAG: Add/remove products

### ISSUE THREAD

**Issue by Aylamccarthy** [Aylamccarthy/madisons-patisserie#15]
## Description: 
As **a user**, I can **add/remove products to my shopping bag** so that **so that I can proceed to checkout**

## Acceptance criteria:
- [x] Users can add/remove products to shopping bag
- [x] Users are navigated to the 'Bag' page as soon as they add an item to their shopping bag

## Tasks
- [x] Create a 'Bag' page
- [x] Add a feature that allows users to add/remove products from their bag
