### ISSUE TITLE
USER STORY: SHOPPING BAG: price details and quantity

### ISSUE THREAD

**Issue by Aylamccarthy** [Aylamccarthy/madisons-patisserie#16]
## Description: 
As **a user**, I can **see all the products details such as price and quantity** so that **I know exactly what I am purchasing**

## Acceptance criteria:
- [x] A user can edit the products' quantity
- [x] A user can easily see a product price

## Tasks
- [x] Implement a feature that allows users to edit the quantity of products they wish to purchase
- [x] Add a section with price details
