### ISSUE TITLE
USER STORY: CHECKOUT: Product and delivery details

### ISSUE THREAD

**Issue by Aylamccarthy** [Aylamccarthy/madisons-patisserie#17]
## Description: 
As **a user**, I can **see and edit my default delivery address for my order** so that  **I can be sure that my details are correct**

## Acceptance criteria:
- [x] Users are navigated to the checkout page accordingly
- [x] Users can easily fill in the form for personal, delivery and payment details

## Tasks
- [x] Create CHECKOUT page
- [x] Add form for for personal, delivery and payment details
- [x] Add form validation
