### ISSUE TITLE
USER STORY:  Initial Project SETUP

### ISSUE THREAD

**Issue by Aylamccarthy** [Aylamccarthy/madisons-patisserie#2]
As **a developer**, I can **set up Django and deploy the site** so that **I can ensure that  the  ground works are done.**

# Acceptance criteria:
- [x] Ensure the Django is successfully set up
- [x] Ensure that the app is successfully deployed in Heroku
- [x]  Ensure AWS and heroku are wired up

# Tasks
- [x] Set up Django
- [x]  Deploy app to Heroku
- [x] Create github workspace
- [x] Set up AWS and wire it up to heroku
