### ISSUE TITLE
USER STORY: USER PROFILE: Order history

### ISSUE THREAD

**Issue by Aylamccarthy** [Aylamccarthy/madisons-patisserie#20]
## Description: 
As **a logged in user**, I can **see my orders history** so that **I can easily keep track of my purchases**

## Acceptance criteria:
- [x] Logged in users can view their order history
- [x] Logged in users can view all the products specifications

## Tasks
- [x] Add a section with information for orders history
- [x] Add a page that displays all products specifications and price
