### ISSUE TITLE
USER STORY: MANAGE ORDER PAGE: Admin order management

### ISSUE THREAD

**Issue by Aylamccarthy** [Aylamccarthy/madisons-patisserie#21]
## Description: 
As **an admin**, I can **see all the orders filtered by date** so that **I can keep track and manage all orders efficiently**

## Acceptance criteria:
- [x] An admin can see full details of every order placed on the website
- [x] An admin can filter the orders by date

## Tasks
- [x] Create MANAGE ORDERS page to display all orders
- [x] Implement filtering by date form
- [x] Add a page that displays full specifications for any order
