### ISSUE TITLE
USER STORY: VOUCHERS

### ISSUE THREAD

**Issue by Aylamccarthy** [Aylamccarthy/madisons-patisserie#22]
## Description: 
As **a user**, I can **avail of vouchers** so that **I can add them to my order**

## Acceptance criteria:
- [x] Users can avail of  20% discount vouchers when they register on the website
- [x] Users can use the vouchers on any purchase on the website as they please

## Tasks
- [x] Implement a feature sending an email with 20% discount code to users that registers on the website.
- [x] Add voucher form on the BAG page
- [x] Add form validation
