### ISSUE TITLE
USER STORY: ADVERTISEMENT: Madison's Pattisserie Facebook Page

### ISSUE THREAD

**Issue by Aylamccarthy** [Aylamccarthy/madisons-patisserie#23]
## Description: 
As **a user**, I can **see the business'  facebook page** so that **I can gain additional information about the business**

## Acceptance criteria:
- [x] Users can navigate to the business' facebook page
- [x] The facebook page reflects the website's theme and all additional relevant information are present

## Tasks
- [x] Create 'Madison's Pattisserie  Facebook page
- [x] Create a link from the website that brings the user to the facebook page
- [x] Include screenshots of the facebook page on readme file
