### ISSUE TITLE
USER STORY: FAQ's

### ISSUE THREAD

**Issue by Aylamccarthy** [Aylamccarthy/madisons-patisserie#24]
## Description: 
As **a user**, I can **go to the FAQ's page** so that **my relevant questions will be answered without me contacting the bakeshop**

## Acceptance criteria:
- [x] The website has a FAQ's page
- [x] Presence of relevant information and frequently asked questions

## Tasks
- [x] Create FAQ's page
- [x] Register FAQ's app to admin
