### ISSUE TITLE
USER STORY: Manual and Automated Testing

### ISSUE THREAD

**Issue by Aylamccarthy** [Aylamccarthy/madisons-patisserie#25]
## Description: 
As **the developer**, I can **perform manual and automated testing** so that **I can ensure optimum application performance**

## Acceptance criteria:
- [x] Well documented manual testing
- [x] Well documented automated testing
## Tasks
- [x] Perform thorough manual  testing
- [x] Perform thorough automated testing
- [x] Include screenshots of automated testing results on testing.md file
