### ISSUE TITLE
USER STORY: Refactoring and Final Deployment

### ISSUE THREAD

**Issue by Aylamccarthy** [Aylamccarthy/madisons-patisserie#26]
## Description: 
As **the developer**, I can **deploy my website successfully** so that **I can easily share it to everyone**

## Acceptance criteria:
- [x] The website successfully deployed to heroku
- [x] The project is free from commented out code, typos and unnecessary files
- [x] No sensitive information being exposed
- [x] Ensure DEBUG=FALSE 

## Tasks
- [x] Perform final code refactoring
- [x] Ensure the project is successfully deployed to heroku
- [x] Turn debug off
- [x] Run final validation tests
