### ISSUE TITLE
USER STORY: Wedding Cake - Enquiry Form

### ISSUE THREAD

**Issue by Aylamccarthy** [Aylamccarthy/madisons-patisserie#27]
## Description: 
As **a user**, I can **fill in a wedding cake enquiry form** so that **I can let the bakeshop know of my interest to order a custom made wedding cake**

## Acceptance criteria:
- [ ] A wedding cake page is present with all the relevant information
- [ ] There is an enquiry form so that a user can fill and submit it to let the bakeshop know if their interest

## Tasks
- [ ] Create a 'Wedding cakes' page
- [ ] Create an enquiry form available for users to fill in and submit
- [ ] Register the app to the admin

**Comment by Aylamccarthy** [comment]
Due to time constraints, this user story will not be implemented at this time but will be implemented in the projects future release.
