### ISSUE TITLE
USER STORY: CONTACT PAGE

### ISSUE THREAD

**Issue by Aylamccarthy** [Aylamccarthy/madisons-patisserie#28]
## Description: 
As **a user**, I can **navigate to the website's contact page** so that **I can get their contact number, location and opening hours**

## Acceptance criteria:
- [x] The website has a contact page
- [x] The contact page has all the relevant information such as contact number, location and opening hours

## Tasks
- [x] Create a contact page
- [x] Ensure contact all the relevant information are present
