### ISSUE TITLE
USER STORY: Create Navigation Menu

### ISSUE THREAD

**Issue by Aylamccarthy** [Aylamccarthy/madisons-patisserie#3]
As **a user**, I can **navigate easily to a navigation menu** so that  **I  can easily navigate through the website content**

# Acceptance criteria:
- [x]  The navigation menu is clear and intuitive
- [x] Relevant information of the bakeshop such as name, slogan, and 'about us' section

# Tasks
- [x] Create a navigation menu
- [x] Add shop's name, motto, and 'about us' section
- [x]  Create custom pages for  404.html, 500.html and 403.html error messages
