### ISSUE TITLE
USER STORY: Typography and colour schemes

### ISSUE THREAD

**Issue by Aylamccarthy** [Aylamccarthy/madisons-patisserie#4]
As  **a user**, I want **the website to have a nice and intuitive design** so that **navigating through the website content is a pleasurable experience.**

# Acceptance criteria:
- [x] The website content has intuitive design that matches the bakeshop's theme
- [x] Fonts and color schemes work in harmony to create a visually appealing content

# Tasks
- [x] Choose relevant color scheme
- [x] Choose fonts 
- [x] Choose images to be used
- [x] add favicon
