### ISSUE TITLE
USER STORY: User SIGN UP/LOGIN

### ISSUE THREAD

**Issue by Aylamccarthy** [Aylamccarthy/madisons-patisserie#5]
As  **a user**, I can **Sign up and Login to my account** so that **I can enjoy the full benefits the website has to offer.**

# Acceptance criteria:
- [x] The user can successfully sign up
- [x] The user can successfully login to/logout from his/her account
- [x]  The user could be authenticated using email and password

# Tasks
- [x] Implement 'Sign Up/Login' feature  using django-allauth module
- [x] Create Sign 'Up/Login' page.
- [x] Create Logout modal.
