### ISSUE TITLE
USER STORY: FOOTER

### ISSUE THREAD

**Issue by Aylamccarthy** [Aylamccarthy/madisons-patisserie#7]
## Description: 
As **a user**, I can **see a footer with relevant information and social media links** so that **I can navigate to the business' social media links**

## Acceptance criteria:
- [x] The website has different clickable social media links on the footer
- [x] Presence of other relevant information such as address and contact details

## Tasks
- [x] Add footer with social media links
- [x] Add newsletter section on the footer and other  relevant links
