### ISSUE TITLE
USER STORY: NEWSLETTER

### ISSUE THREAD

**Issue by Aylamccarthy** [Aylamccarthy/madisons-patisserie#8]
## Description: 
As **a user**, I can **subscribe to a newsletter** so that **I can always be up to date with the latest news and promotions**

## Acceptance criteria:
- [x] The website has a newsletter section
- [x] A user should be able to subscribe to a newsletter

## Tasks
- [x] Create news letter form utilising mailchimp
- [x] Add newsletter section
